language: python
dist: xenial

stages:
  - quality
  - test

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

matrix:
  fast_finish: true
  include:
      - { python: "3.6", env: DJANGO=1.11 TOXENV=py36-django111 }
      - { python: "3.6", env: DJANGO=2.2 TOXENV=py36-django22 }
      - { python: "3.6", env: DJANGO=3.0 TOXENV=py36-django30 }

      - { python: "3.7", env: DJANGO=1.11 TOXENV=py37-django111 }
      - { python: "3.7", env: DJANGO=2.2 TOXENV=py37-django22 }
      - { python: "3.7", env: DJANGO=3.0 TOXENV=py37-django30 }

      - { python: "3.8", env: DJANGO=1.11 TOXENV=py38-django111 }
      - { python: "3.8", env: DJANGO=2.2 TOXENV=py38-django22 }
      - { python: "3.8", env: DJANGO=3.0 TOXENV=py38-django30 }

      - { python: "3.7", env: TOXENV=quality }

before_install:
  - pip install codecov

install:
  - pip install pip -U
  - pip install tox-travis
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

script:
  - tox

after_script:
  - bash ./scripts/travis_telegram_notification.sh

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
    email: false
