language: python
dist: xenial

stages:
  - quality
  - test

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

matrix:
  fast_finish: true
  include:
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }

      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }

      - { python: "3.6", env: TOXENV=quality }

before_install:
  - pip install codecov

install:
  - pip install pip -U
  - pip install tox-travis
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
    email: false
